### ISSUE TITLE
Stamp_make result not initialized

### ISSUE THREAD

**Issue by jorisbontje** [patham9/ANSNA#19] opened 2018-10-02 21:45 UTC
https://github.com/patham9/ANSNA/blob/master/src/Stamp.c

`Stamp_make` should initialize `ret` by calling `Stamp_RESET` on it first, before zipping, otherwise parts of the result evidentalBase could contain zero values rather than `STAMP_FREE`, which will causes false positives on `Stamp_checkOverlap` calls (due to it matching on 0 from non-initialized parts rather than breaking at the "end" of an evidentalBase)

**Comment by patham9** [comment] 2018-10-03 00:02
Hm I guess the issue is that STAMP_FREE should be 0 and not -1. Thinking about this again, all data structures should be initializable by simply setting    test = {0};, making all the RESET functions obsolete. What do you think?

**Comment by patham9** [comment] 2018-10-03 00:18
Fixed by https://github.com/patham9/ANSNA/commit/33ac967e0385777b3502cfeb47096404e2c92681

**Closed as completed by patham9** 2018-10-03 00:18 UTC
